### ISSUE TITLE
Feature request: Add example with real data

### ISSUE THREAD

**Issue by inkenbrandt** [radwinskis/RSAbs#1]
This is a very nice package.  I like how you leverage the Pandas library. I think it would be very helpful to include a Jupyter Notebook with an example of your functions and their output.  I noticed that the input for your key functions are Pandas dataframes, and would like to see how you go from the source data to the Pandas dataframe format.

**Comment by radwinskis** [comment]
> This is a very nice package. I like how you leverage the Pandas library. I think it would be very helpful to include a Jupyter Notebook with an example of your functions and their output. I noticed that the input for your key functions are Pandas dataframes, and would like to see how you go from the source data to the Pandas dataframe format.

Great idea, I will add some examples to the readme and will include some demo files.
Thanks for the comments!

**Comment by radwinskis** [comment]
An example Jupyter Notebook and csv file with 5 spectra have been added to a demo folder in the repo directory, and I added to the readme showing the code and results from the example Jupyter Notebook. Hope it is helpful! Will add more later when I get a chance. Have more ideas for some fun features! (Note: I haven't added the new files to pypi yet)

**Comment by inkenbrandt** [comment]
That is extremely helpful. That was fast! Thank you!
